version: 2.1
workflows:
  build_test_deploy:
    jobs:
      - build
      - test-python-install:
          name: test-python-install-3.4
          version: "3.4"
          requires:
            - build
      - test-python-install:
          name: test-python-install-3.5
          version: "3.5"
          requires:
            - build
      - test-python-install:
          name: test-python-install-3.6
          version: "3.6"
          requires:
            - build
      - test-python-install:
          name: test-python-install-3.7
          version: "3.7"
          requires:
            - build
      - test-python-install:
          name: test-python-install-3.8
          version: "3.8"
          requires:
            - build
      - test-python-install:
          name: test-python-install-3.9
          version: "3.9"
          requires:
            - build
      - deploy:
          requires:
            - build
            - test-python-install-3.4
            - test-python-install-3.5
            - test-python-install-3.6
            - test-python-install-3.7
            - test-python-install-3.8
            - test-python-install-3.9
          filters:
            branches:
              only:
                - main

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
      - run:
          name: install python dependencies
          command: |
            make dev
      - run:
          name: "Sets virtualenv path"
          command: echo 'export VIRTUALENV_PATH=`pipenv --virtualenv`' >> $BASH_ENV
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
          paths:
            - ${VIRTUALENV_PATH}
      - run:
          name: run tests
          command: |
            make test
      - store_artifacts:
          path: htmlcov/

  test-python-install:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: circleci/python:<< parameters.version >>
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
      - run:
          name: install python dependencies
          command: |
            make dev
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
          paths:
            - ${VIRTUALENV_PATH}
      - run:
          name: run tests
          command: |
            make test
      - store_artifacts:
          path: htmlcov/

  deploy:
    docker:
      - image: circlecli/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
      - run:
          name: install python dependencies
          command: |
            make dev
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
          paths:
            - ${VIRTUALENV_PATH}
      - run:
          name: verify git tag vs. version
          command: |
            python setup.py verify
      - run:
          name: create package
          command: |
            make package
      - run:
          name: upload to pypi
          command: |
            twine upload dist/*
